title: I'm Working on It
theme: minima
show_excerpts: true
author: "Nico Appel"
keep_files:
  - assets/docs/*.md
minima:
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/nicoappel"
    - title: Twitter
      icon: x-twitter
      url: "https://x.com/nicoappel"
    - title: LinkedIn
      icon: fa-linkedin
      url: "https://www.linkedin.com/in/nico-appel/"
    - title: Substack
      icon: substack
      url: "https://substack.com/@nicoappel"
