title: I'm Working on It
theme: minima
show_excerpts: true
author: "Nico Appel"
keep_files:
  - assets/docs/*.md
github_username: nicoappel
twitter_username: nicoappel
linkedin_username: in/nico-appel
